//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_reservation_extra_features
    {
        public int id { get; set; }
        public int fk_room_reservation { get; set; }
        public int fk_extra_feature { get; set; }
    
        public virtual Extra_features Extra_features { get; set; }
        public virtual Room_reservation_extra_features Room_reservation_extra_features1 { get; set; }
        public virtual Room_reservation_extra_features Room_reservation_extra_features2 { get; set; }
    }
}
