//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_images
    {
        public int id { get; set; }
        public int fk_room { get; set; }
        public byte[] imagePath { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
