//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.room_reservations = new HashSet<room_reservations>();
        }
    
        public int id { get; set; }
        public System.DateTime dateFrom { get; set; }
        public System.DateTime dateTo { get; set; }
        public System.TimeSpan timeFrom { get; set; }
        public System.TimeSpan timeTo { get; set; }
        public int fk_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_reservations> room_reservations { get; set; }
    }
}
