//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_reservations
    {
        public int id { get; set; }
        public int fk_room { get; set; }
        public int fk_reservation { get; set; }
        public int fk_payment { get; set; }
        public string observations { get; set; }
        public string status { get; set; }
        public bool deleted { get; set; }
    
        public virtual payment payment { get; set; }
        public virtual reservation reservation { get; set; }
        public virtual room room { get; set; }
    }
}
